title: Stackbit Book Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_type: boxed
style: classic
palette: gray
mode: light
base_font: serif
header:
  title: Marketing Playbook
  logo: images/logo.svg
  logo_alt: Marketing Playbook logo
  has_primary_nav: true
  primary_nav_links:
    - label: Pricing
      url: /pricing
      style: link
    - label: Story
      url: /story
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
  has_secondary_nav: true
  secondary_nav_links:
    - label: Start Learning
      url: /thank-you
      style: primary
  has_anncmnt: true
  anncmnt_content: >-
    Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
    More](/pricing/)**
  anncmnt_align: left
  anncmnt_is_home_only: true
  anncmnt_has_close: true
  anncmnt_id: new-features
footer:
  logo: images/logo.svg
  logo_alt: Marketing Playbook logo
  has_primary_nav: true
  primary_nav_title: Company
  primary_nav_links:
    - label: Story
      url: /story
      style: link
    - label: Pricing
      url: /pricing
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
  has_secondary_nav: true
  secondary_nav_title: Legal
  secondary_nav_links:
    - label: Terms & Conditions
      url: /terms-conditions
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  has_tertiary_nav: false
  has_social: true
  social_links:
    - label: Facebook
      url: 'https://www.facebook.com/'
      style: link
      has_icon: true
      icon: facebook
      icon_position: center
      new_window: true
    - label: Vimeo
      url: 'https://vimeo.com/'
      style: link
      has_icon: true
      icon: vimeo
      icon_position: center
      new_window: true
    - label: lorem-ipsum
      url: '#'
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: right
      new_window: false
      no_follow: false
      type: action
    - label: lorem-ipsum
      url: '#'
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: right
      new_window: false
      no_follow: false
      type: action
    - label: lorem-ipsum
      url: '#'
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: right
      new_window: false
      no_follow: false
      type: action
  content: '&copy; Big Science Publishing. All rights reserved. '
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
domain: 'https://smiling-cabbage-e6005.netlify.app'
